
select
    ticker
    , calendar_dt
    , open
    , high
    , low
    , close
    , yday1_date
    , yday2_date
    , yday3_date
    , yday4_date
    , yday5_date
    , week_start
    , d1oo
    , d2oo
    , d3oo
    , d4oo
    , d5oo
    , d1oo_pos
    , d2oo_pos
    , d3oo_pos
    , d4oo_pos
    , d5oo_pos
    , d1oc
    , d2oc
    , d3oc
    , d4oc
    , d5oc
    , d1oc_pos
    , d2oc_pos
    , d3oc_pos
    , d4oc_pos
    , d5oc_pos
    , d1co
    , d2co
    , d3co
    , d4co
    , d5co
    , d1co_pos
    , d2co_pos
    , d3co_pos
    , d4co_pos
    , d5co_pos
    , d1cc
    , d2cc
    , d3cc
    , d4cc
    , d5cc
    , d1cc_pos
    , d2cc_pos
    , d3cc_pos
    , d4cc_pos
    , d5cc_pos
    , d1oo_pct_100d
    , d2oo_pct_100d
    , d3oo_pct_100d
    , d4oo_pct_100d
    , d5oo_pct_100d
    , d1oc_pct_100d
    , d2oc_pct_100d
    , d3oc_pct_100d
    , d4oc_pct_100d
    , d5oc_pct_100d
    , d1co_pct_100d
    , d2co_pct_100d
    , d3co_pct_100d
    , d4co_pct_100d
    , d5co_pct_100d
    , d1cc_pct_100d
    , d2cc_pct_100d
    , d3cc_pct_100d
    , d4cc_pct_100d
    , d5cc_pct_100d
    , d1oo_streak
    , d2oo_streak
    , d3oo_streak
    , d4oo_streak
    , d5oo_streak
    , d1oc_streak
    , d2oc_streak
    , d3oc_streak
    , d4oc_streak
    , d5oc_streak
    , d1co_streak
    , d2co_streak
    , d3co_streak
    , d4co_streak
    , d5co_streak
    , d1cc_streak
    , d2cc_streak
    , d3cc_streak
    , d4cc_streak
    , d5cc_streak

FROM price_calcs.int_daily_metrics

where calendar_dt >= current_date - 400

order by ticker, calendar_dt